#!/bin/bash

set -euo pipefail

printenv

#echo "--- Build RPM spec: ${BUILDKITE_PLIGIN_RPMBUILD_SPEC}"

command = "rpmdev-setuptree; rpmbuild -ba test.spec"

docker run -it --rm \
    --volume "" \
    "rpmbuild/centos7" bash -c $command
